# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(940, 560))
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.styleSheet.setFont(font)
        self.styleSheet.setStyleSheet("/*\n"
                                      "                    /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "\n"
                                      "                    SET APP STYLESHEET - FULL STYLES HERE\n"
                                      "                    DARK THEME - DRACULA COLOR BASED\n"
                                      "\n"
                                      "                    ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
                                      "\n"
                                      "                    QWidget{\n"
                                      "                    color: rgb(221, 221, 221);\n"
                                      "                    font: 12pt \"Segoe UI\";\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    Tooltip */\n"
                                      "                    QToolTip {\n"
                                      "                    color: #ffffff;\n"
                                      "                    background-color: rgba(33, 37, 43, 180);\n"
                                      "                    border: 1px solid rgb(44, 49, 58);\n"
                                      "                    background-image: none;\n"
                                      "                    background-position: left center;\n"
                                      "                    background-repeat: no-repeat;\n"
                                      "                    border: none;\n"
                                      "                    border-left: 2px solid rgb(255, 121, 198);\n"
                                      "                    text-align: left;\n"
                                      "                    padding-left: 8px;\n"
                                      "                    margin: 0px;\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    Bg App */\n"
                                      "                    #bgApp {\n"
                                      "                    background-color: rgb(40, 44, 52);\n"
                                      "                    border: 1px solid rgb(44, 49, 58);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    Left Menu */\n"
                                      "                    #leftMenuBg {\n"
                                      "                    background-color: rgb(33, 37, 43);\n"
                                      "                    }\n"
                                      "                    #topLogo {\n"
                                      "                    background-color: rgb(33, 37, 43);\n"
                                      "                    background-image: url(:/images/images/images/PyDracula.png);\n"
                                      "                    background-position: centered;\n"
                                      "                    background-repeat: no-repeat;\n"
                                      "                    }\n"
                                      "                    #titleLeftApp { font: 63 12pt \"Segoe UI Semibold\"; }\n"
                                      "                    #titleLeftDescription { font: 8pt \"Segoe UI\"; color: rgb(189, 147, 249); }\n"
                                      "\n"
                                      "                    /* MENUS */\n"
                                      "                    #topMenu .QPushButton {\n"
                                      "                    background-position: left center;\n"
                                      "                    background-repeat: no-repeat;\n"
                                      "                    border: none;\n"
                                      "                    border-left: 22px solid transparent;\n"
                                      "                    background-color: transparent;\n"
                                      "                    text-align: left;\n"
                                      "                    padding-left: 44px;\n"
                                      "                    }\n"
                                      "                    #topMenu .QPushButton:hover {\n"
                                      "                    background-color: rgb(40, 44, 52);\n"
                                      "                    }\n"
                                      "                    #topMenu .QPushButton:pressed {\n"
                                      "                    background-color: rgb(189, 147, 249);\n"
                                      "                    color: rgb(255, 255, 255);\n"
                                      "                    }\n"
                                      "                    #bottomMenu .QPushButton {\n"
                                      "                    background-position: left center;\n"
                                      "                    background-repeat: no-repeat;\n"
                                      "                    border: none;\n"
                                      "                    border-left: 20px solid transparent;\n"
                                      "                    background-color:transparent;\n"
                                      "                    text-align: left;\n"
                                      "                    padding-left: 44px;\n"
                                      "                    }\n"
                                      "                    #bottomMenu .QPushButton:hover {\n"
                                      "                    background-color: rgb(40, 44, 52);\n"
                                      "                    }\n"
                                      "                    #bottomMenu .QPushButton:pressed {\n"
                                      "                    background-color: rgb(189, 147, 249);\n"
                                      "                    color: rgb(255, 255, 255);\n"
                                      "                    }\n"
                                      "                    #leftMenuFrame{\n"
                                      "                    border-top: 3px solid rgb(44, 49, 58);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* Toggle Button */\n"
                                      "                    #toggleButton {\n"
                                      "                    background-position: left center;\n"
                                      "                    background-repeat: no-repeat;\n"
                                      "                    border: none;\n"
                                      "                    border-left: 20px solid transparent;\n"
                                      "                    background-color: rgb(37, 41, 48);\n"
                                      "                    text-align: left;\n"
                                      "                    padding-left: 44px;\n"
                                      "                    color: rgb(113, 126, 149);\n"
                                      "                    }\n"
                                      "                    #toggleButton:hover {\n"
                                      "                    background-color: rgb(40, 44, 52);\n"
                                      "                    }\n"
                                      "                    #toggleButton:pressed {\n"
                                      "                    background-color: rgb(189, 147, 249);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* Title Menu */\n"
                                      "                    #titleRightInfo { padding-left: 10px; }\n"
                                      "\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    Extra Tab */\n"
                                      "                    #extraLeftBox {\n"
                                      "                    background-color: rgb(44, 49, 58);\n"
                                      "                    }\n"
                                      "                    #extraTopBg{\n"
                                      "                    background-color: rgb(189, 147, 249)\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* Icon */\n"
                                      "                    #extraIcon {\n"
                                      "                    background-position: center;\n"
                                      "                    background-repeat: no-repeat;\n"
                                      "                    background-image: url(:/icons/images/icons/icon_settings.png);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* Label */\n"
                                      "                    #extraLabel { color: rgb(255, 255, 255); }\n"
                                      "\n"
                                      "                    /* Btn Close */\n"
                                      "                    #extraCloseColumnBtn { background-color: rgba(255, 255, 255, 0); border: none; border-radius: 5px; }\n"
                                      "                    #extraCloseColumnBtn:hover { background-color: rgb(196, 161, 249); border-style: solid;\n"
                                      "                    border-radius: 4px; }\n"
                                      "                    #extraCloseColumnBtn:pressed { background-color: rgb(180, 141, 238); border-style: solid;\n"
                                      "                    border-radius: 4px; }\n"
                                      "\n"
                                      "                    /* Extra Content */\n"
                                      "                    #extraContent{\n"
                                      "                    border-top: 3px solid rgb(40, 44, 52);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* Extra Top Menus */\n"
                                      "                    #extraTopMenu .QPushButton {\n"
                                      "                    background-position: left center;\n"
                                      "                    background-repeat: no-repeat;\n"
                                      "                    border: none;\n"
                                      "                    border-left: 22px solid transparent;\n"
                                      "                    background-color:transparent;\n"
                                      "                    text-align: left;\n"
                                      "                    padding-left: 44px;\n"
                                      "                    }\n"
                                      "                    #extraTopMenu .QPushButton:hover {\n"
                                      "                    background-color: rgb(40, 44, 52);\n"
                                      "                    }\n"
                                      "                    #extraTopMenu .QPushButton:pressed {\n"
                                      "                    background-color: rgb(189, 147, 249);\n"
                                      "                    color: rgb(255, 255, 255);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    Content App */\n"
                                      "                    #contentTopBg{\n"
                                      "                    background-color: rgb(33, 37, 43);\n"
                                      "                    }\n"
                                      "                    #contentBottom{\n"
                                      "                    border-top: 3px solid rgb(44, 49, 58);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* Top Buttons */\n"
                                      "                    #rightButtons .QPushButton { background-color: rgba(255, 255, 255, 0); border: none; border-radius:\n"
                                      "                    5px; }\n"
                                      "                    #rightButtons .QPushButton:hover { background-color: rgb(44, 49, 57); border-style: solid;\n"
                                      "                    border-radius: 4px; }\n"
                                      "                    #rightButtons .QPushButton:pressed { background-color: rgb(23, 26, 30); border-style: solid;\n"
                                      "                    border-radius: 4px; }\n"
                                      "\n"
                                      "                    /* Theme Settings */\n"
                                      "                    #extraRightBox { background-color: rgb(44, 49, 58); }\n"
                                      "                    #themeSettingsTopDetail { background-color: rgb(189, 147, 249); }\n"
                                      "\n"
                                      "                    /* Bottom Bar */\n"
                                      "                    #bottomBar { background-color: rgb(44, 49, 58); }\n"
                                      "                    #bottomBar QLabel { font-size: 11px; color: rgb(113, 126, 149); padding-left: 10px; padding-right:\n"
                                      "                    10px; padding-bottom: 2px; }\n"
                                      "\n"
                                      "                    /* CONTENT SETTINGS */\n"
                                      "                    /* MENUS */\n"
                                      "                    #contentSettings .QPushButton {\n"
                                      "                    background-position: left center;\n"
                                      "                    background-repeat: no-repeat;\n"
                                      "                    border: none;\n"
                                      "                    border-left: 22px solid transparent;\n"
                                      "                    background-color:transparent;\n"
                                      "                    text-align: left;\n"
                                      "                    padding-left: 44px;\n"
                                      "                    }\n"
                                      "                    #contentSettings .QPushButton:hover {\n"
                                      "                    background-color: rgb(40, 44, 52);\n"
                                      "                    }\n"
                                      "                    #contentSettings .QPushButton:pressed {\n"
                                      "                    background-color: rgb(189, 147, 249);\n"
                                      "                    color: rgb(255, 255, 255);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    QTableWidget */\n"
                                      "                    QTableWidget {\n"
                                      "                    background-color: transparent;\n"
                                      "                    padding: 10px;\n"
                                      "                    border-radius: 5px;\n"
                                      "                    gridline-color: rgb(44, 49, 58);\n"
                                      "                    border-bottom: 1px solid rgb(44, 49, 60);\n"
                                      "                    }\n"
                                      "                    QTableWidget::item{\n"
                                      "                    border-color: rgb(44, 49, 60);\n"
                                      "                    padding-left: 5px;\n"
                                      "                    padding-right: 5px;\n"
                                      "                    gridline-color: rgb(44, 49, 60);\n"
                                      "                    }\n"
                                      "                    QTableWidget::item:selected{\n"
                                      "                    background-color: rgb(189, 147, 249);\n"
                                      "                    }\n"
                                      "                    QHeaderView::section{\n"
                                      "                    background-color: rgb(33, 37, 43);\n"
                                      "                    max-width: 30px;\n"
                                      "                    border: 1px solid rgb(44, 49, 58);\n"
                                      "                    border-style: none;\n"
                                      "                    border-bottom: 1px solid rgb(44, 49, 60);\n"
                                      "                    border-right: 1px solid rgb(44, 49, 60);\n"
                                      "                    }\n"
                                      "                    QTableWidget::horizontalHeader {\n"
                                      "                    background-color: rgb(33, 37, 43);\n"
                                      "                    }\n"
                                      "                    QHeaderView::section:horizontal\n"
                                      "                    {\n"
                                      "                    border: 1px solid rgb(33, 37, 43);\n"
                                      "                    background-color: rgb(33, 37, 43);\n"
                                      "                    padding: 3px;\n"
                                      "                    border-top-left-radius: 7px;\n"
                                      "                    border-top-right-radius: 7px;\n"
                                      "                    }\n"
                                      "                    QHeaderView::section:vertical\n"
                                      "                    {\n"
                                      "                    border: 1px solid rgb(44, 49, 60);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    LineEdit */\n"
                                      "                    QLineEdit {\n"
                                      "                    background-color: rgb(33, 37, 43);\n"
                                      "                    border-radius: 5px;\n"
                                      "                    border: 2px solid rgb(33, 37, 43);\n"
                                      "                    padding-left: 10px;\n"
                                      "                    selection-color: rgb(255, 255, 255);\n"
                                      "                    selection-background-color: rgb(255, 121, 198);\n"
                                      "                    }\n"
                                      "                    QLineEdit:hover {\n"
                                      "                    border: 2px solid rgb(64, 71, 88);\n"
                                      "                    }\n"
                                      "                    QLineEdit:focus {\n"
                                      "                    border: 2px solid rgb(91, 101, 124);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    PlainTextEdit */\n"
                                      "                    QPlainTextEdit {\n"
                                      "                    background-color: rgb(27, 29, 35);\n"
                                      "                    border-radius: 5px;\n"
                                      "                    padding: 10px;\n"
                                      "                    selection-color: rgb(255, 255, 255);\n"
                                      "                    selection-background-color: rgb(255, 121, 198);\n"
                                      "                    }\n"
                                      "                    QPlainTextEdit QScrollBar:vertical {\n"
                                      "                    width: 8px;\n"
                                      "                    }\n"
                                      "                    QPlainTextEdit QScrollBar:horizontal {\n"
                                      "                    height: 8px;\n"
                                      "                    }\n"
                                      "                    QPlainTextEdit:hover {\n"
                                      "                    border: 2px solid rgb(64, 71, 88);\n"
                                      "                    }\n"
                                      "                    QPlainTextEdit:focus {\n"
                                      "                    border: 2px solid rgb(91, 101, 124);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    ScrollBars */\n"
                                      "                    QScrollBar:horizontal {\n"
                                      "                    border: none;\n"
                                      "                    background: rgb(52, 59, 72);\n"
                                      "                    height: 8px;\n"
                                      "                    margin: 0px 21px 0 21px;\n"
                                      "                    border-radius: 0px;\n"
                                      "                    }\n"
                                      "                    QScrollBar::handle:horizontal {\n"
                                      "                    background: rgb(189, 147, 249);\n"
                                      "                    min-width: 25px;\n"
                                      "                    border-radius: 4px\n"
                                      "                    }\n"
                                      "                    QScrollBar::add-line:horizontal {\n"
                                      "                    border: none;\n"
                                      "                    background: rgb(55, 63, 77);\n"
                                      "                    width: 20px;\n"
                                      "                    border-top-right-radius: 4px;\n"
                                      "                    border-bottom-right-radius: 4px;\n"
                                      "                    subcontrol-position: right;\n"
                                      "                    subcontrol-origin: margin;\n"
                                      "                    }\n"
                                      "                    QScrollBar::sub-line:horizontal {\n"
                                      "                    border: none;\n"
                                      "                    background: rgb(55, 63, 77);\n"
                                      "                    width: 20px;\n"
                                      "                    border-top-left-radius: 4px;\n"
                                      "                    border-bottom-left-radius: 4px;\n"
                                      "                    subcontrol-position: left;\n"
                                      "                    subcontrol-origin: margin;\n"
                                      "                    }\n"
                                      "                    QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
                                      "                    {\n"
                                      "                    background: none;\n"
                                      "                    }\n"
                                      "                    QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
                                      "                    {\n"
                                      "                    background: none;\n"
                                      "                    }\n"
                                      "                    QScrollBar:vertical {\n"
                                      "                    border: none;\n"
                                      "                    background: rgb(52, 59, 72);\n"
                                      "                    width: 8px;\n"
                                      "                    margin: 21px 0 21px 0;\n"
                                      "                    border-radius: 0px;\n"
                                      "                    }\n"
                                      "                    QScrollBar::handle:vertical {\n"
                                      "                    background: rgb(189, 147, 249);\n"
                                      "                    min-height: 25px;\n"
                                      "                    border-radius: 4px\n"
                                      "                    }\n"
                                      "                    QScrollBar::add-line:vertical {\n"
                                      "                    border: none;\n"
                                      "                    background: rgb(55, 63, 77);\n"
                                      "                    height: 20px;\n"
                                      "                    border-bottom-left-radius: 4px;\n"
                                      "                    border-bottom-right-radius: 4px;\n"
                                      "                    subcontrol-position: bottom;\n"
                                      "                    subcontrol-origin: margin;\n"
                                      "                    }\n"
                                      "                    QScrollBar::sub-line:vertical {\n"
                                      "                    border: none;\n"
                                      "                    background: rgb(55, 63, 77);\n"
                                      "                    height: 20px;\n"
                                      "                    border-top-left-radius: 4px;\n"
                                      "                    border-top-right-radius: 4px;\n"
                                      "                    subcontrol-position: top;\n"
                                      "                    subcontrol-origin: margin;\n"
                                      "                    }\n"
                                      "                    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
                                      "                    background: none;\n"
                                      "                    }\n"
                                      "\n"
                                      "                    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
                                      "                    background: none;\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    CheckBox */\n"
                                      "                    QCheckBox::indicator {\n"
                                      "                    border: 3px solid rgb(52, 59, 72);\n"
                                      "                    width: 15px;\n"
                                      "                    height: 15px;\n"
                                      "                    border-radius: 10px;\n"
                                      "                    background: rgb(44, 49, 60);\n"
                                      "                    }\n"
                                      "                    QCheckBox::indicator:hover {\n"
                                      "                    border: 3px solid rgb(58, 66, 81);\n"
                                      "                    }\n"
                                      "                    QCheckBox::indicator:checked {\n"
                                      "                    background: 3px solid rgb(52, 59, 72);\n"
                                      "                    border: 3px solid rgb(52, 59, 72);\n"
                                      "                    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    RadioButton */\n"
                                      "                    QRadioButton::indicator {\n"
                                      "                    border: 3px solid rgb(52, 59, 72);\n"
                                      "                    width: 15px;\n"
                                      "                    height: 15px;\n"
                                      "                    border-radius: 10px;\n"
                                      "                    background: rgb(44, 49, 60);\n"
                                      "                    }\n"
                                      "                    QRadioButton::indicator:hover {\n"
                                      "                    border: 3px solid rgb(58, 66, 81);\n"
                                      "                    }\n"
                                      "                    QRadioButton::indicator:checked {\n"
                                      "                    background: 3px solid rgb(94, 106, 130);\n"
                                      "                    border: 3px solid rgb(52, 59, 72);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    ComboBox */\n"
                                      "                    QComboBox{\n"
                                      "                    background-color: rgb(27, 29, 35);\n"
                                      "                    border-radius: 5px;\n"
                                      "                    border: 2px solid rgb(33, 37, 43);\n"
                                      "                    padding: 5px;\n"
                                      "                    padding-left: 10px;\n"
                                      "                    }\n"
                                      "                    QComboBox:hover{\n"
                                      "                    border: 2px solid rgb(64, 71, 88);\n"
                                      "                    }\n"
                                      "                    QComboBox::drop-down {\n"
                                      "                    subcontrol-origin: padding;\n"
                                      "                    subcontrol-position: top right;\n"
                                      "                    width: 25px;\n"
                                      "                    border-left-width: 3px;\n"
                                      "                    border-left-color: rgba(39, 44, 54, 150);\n"
                                      "                    border-left-style: solid;\n"
                                      "                    border-top-right-radius: 3px;\n"
                                      "                    border-bottom-right-radius: 3px;\n"
                                      "                    background-image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
                                      "                    background-position: center;\n"
                                      "                    background-repeat: no-reperat;\n"
                                      "                    }\n"
                                      "                    QComboBox QAbstractItemView {\n"
                                      "                    color: rgb(255, 121, 198);\n"
                                      "                    background-color: rgb(33, 37, 43);\n"
                                      "                    padding: 10px;\n"
                                      "                    selection-background-color: rgb(39, 44, 54);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    Sliders */\n"
                                      "                    QSlider::groove:horizontal {\n"
                                      "                    border-radius: 5px;\n"
                                      "                    height: 10px;\n"
                                      "                    margin: 0px;\n"
                                      "                    background-color: rgb(52, 59, 72);\n"
                                      "                    }\n"
                                      "                    QSlider::groove:horizontal:hover {\n"
                                      "                    background-color: rgb(55, 62, 76);\n"
                                      "                    }\n"
                                      "                    QSlider::handle:horizontal {\n"
                                      "                    background-color: rgb(189, 147, 249);\n"
                                      "                    border: none;\n"
                                      "                    height: 10px;\n"
                                      "                    width: 10px;\n"
                                      "                    margin: 0px;\n"
                                      "                    border-radius: 5px;\n"
                                      "                    }\n"
                                      "                    QSlider::handle:horizontal:hover {\n"
                                      "                    background-color: rgb(195, 155, 255);\n"
                                      "                    }\n"
                                      "                    QSlider::handle:horizontal:pressed {\n"
                                      "                    background-color: rgb(255, 121, 198);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    QSlider::groove:vertical {\n"
                                      "                    border-radius: 5px;\n"
                                      "                    width: 10px;\n"
                                      "                    margin: 0px;\n"
                                      "                    background-color: rgb(52, 59, 72);\n"
                                      "                    }\n"
                                      "                    QSlider::groove:vertical:hover {\n"
                                      "                    background-color: rgb(55, 62, 76);\n"
                                      "                    }\n"
                                      "                    QSlider::handle:vertical {\n"
                                      "                    background-color: rgb(189, 147, 249);\n"
                                      "                    border: none;\n"
                                      "                    height: 10px;\n"
                                      "                    width: 10px;\n"
                                      "                    margin: 0px;\n"
                                      "                    border-radius: 5px;\n"
                                      "                    }\n"
                                      "                    QSlider::handle:vertical:hover {\n"
                                      "                    background-color: rgb(195, 155, 255);\n"
                                      "                    }\n"
                                      "                    QSlider::handle:vertical:pressed {\n"
                                      "                    background-color: rgb(255, 121, 198);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    CommandLinkButton */\n"
                                      "                    QCommandLinkButton {\n"
                                      "                    color: rgb(255, 121, 198);\n"
                                      "                    border-radius: 5px;\n"
                                      "                    padding: 5px;\n"
                                      "                    color: rgb(255, 170, 255);\n"
                                      "                    }\n"
                                      "                    QCommandLinkButton:hover {\n"
                                      "                    color: rgb(255, 170, 255);\n"
                                      "                    background-color: rgb(44, 49, 60);\n"
                                      "                    }\n"
                                      "                    QCommandLinkButton:pressed {\n"
                                      "                    color: rgb(189, 147, 249);\n"
                                      "                    background-color: rgb(52, 58, 71);\n"
                                      "                    }\n"
                                      "\n"
                                      "                    /* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
                                      "                    Button */\n"
                                      "                    #pagesContainer QPushButton {\n"
                                      "                    border: 2px solid rgb(52, 59, 72);\n"
                                      "                    border-radius: 5px;\n"
                                      "                    background-color: rgb(52, 59, 72);\n"
                                      "                    }\n"
                                      "                    #pagesContainer QPushButton:hover {\n"
                                      "                    background-color: rgb(57, 65, 80);\n"
                                      "                    border: 2px solid rgb(61, 70, 86);\n"
                                      "                    }\n"
                                      "                    #pagesContainer QPushButton:pressed {\n"
                                      "                    background-color: rgb(35, 40, 49);\n"
                                      "                    border: 2px solid rgb(43, 50, 61);\n"
                                      "                    }\n"
                                      "\n"
                                      "                ")
        self.styleSheet.setObjectName("styleSheet")
        self.appMargins = QtWidgets.QVBoxLayout(self.styleSheet)
        self.appMargins.setContentsMargins(10, 10, 10, 10)
        self.appMargins.setSpacing(0)
        self.appMargins.setObjectName("appMargins")
        self.bgApp = QtWidgets.QFrame(self.styleSheet)
        self.bgApp.setStyleSheet("")
        self.bgApp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bgApp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bgApp.setObjectName("bgApp")
        self.appLayout = QtWidgets.QHBoxLayout(self.bgApp)
        self.appLayout.setContentsMargins(0, 0, 0, 0)
        self.appLayout.setSpacing(0)
        self.appLayout.setObjectName("appLayout")
        self.leftMenuBg = QtWidgets.QFrame(self.bgApp)
        self.leftMenuBg.setMinimumSize(QtCore.QSize(60, 0))
        self.leftMenuBg.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leftMenuBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuBg.setObjectName("leftMenuBg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftMenuBg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topLogoInfo = QtWidgets.QFrame(self.leftMenuBg)
        self.topLogoInfo.setMinimumSize(QtCore.QSize(0, 50))
        self.topLogoInfo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.topLogoInfo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topLogoInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLogoInfo.setObjectName("topLogoInfo")
        self.topLogo = QtWidgets.QFrame(self.topLogoInfo)
        self.topLogo.setGeometry(QtCore.QRect(10, 5, 42, 42))
        self.topLogo.setMinimumSize(QtCore.QSize(42, 42))
        self.topLogo.setMaximumSize(QtCore.QSize(42, 42))
        self.topLogo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLogo.setObjectName("topLogo")
        self.titleLeftApp = QtWidgets.QLabel(self.topLogoInfo)
        self.titleLeftApp.setGeometry(QtCore.QRect(70, 8, 160, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.titleLeftApp.setFont(font)
        self.titleLeftApp.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.titleLeftApp.setObjectName("titleLeftApp")
        self.titleLeftDescription = QtWidgets.QLabel(self.topLogoInfo)
        self.titleLeftDescription.setGeometry(QtCore.QRect(70, 27, 160, 16))
        self.titleLeftDescription.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        self.titleLeftDescription.setFont(font)
        self.titleLeftDescription.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.titleLeftDescription.setObjectName("titleLeftDescription")
        self.verticalLayout_3.addWidget(self.topLogoInfo)
        self.leftMenuFrame = QtWidgets.QFrame(self.leftMenuBg)
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalMenuLayout = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalMenuLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalMenuLayout.setSpacing(0)
        self.verticalMenuLayout.setObjectName("verticalMenuLayout")
        self.toggleBox = QtWidgets.QFrame(self.leftMenuFrame)
        self.toggleBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.toggleBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toggleBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toggleBox.setObjectName("toggleBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.toggleBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toggleButton = QtWidgets.QPushButton(self.toggleBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleButton.sizePolicy().hasHeightForWidth())
        self.toggleButton.setSizePolicy(sizePolicy)
        self.toggleButton.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.toggleButton.setFont(font)
        self.toggleButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                  ))
        self.toggleButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toggleButton.setStyleSheet("background-image:\n"
                                        "                                                                                url(:/icons/images/icons/icon_menu.png);\n"
                                        "                                                                            ")
        self.toggleButton.setObjectName("toggleButton")
        self.verticalLayout_4.addWidget(self.toggleButton)
        self.verticalMenuLayout.addWidget(self.toggleBox)
        self.topMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.topMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMenu.setObjectName("topMenu")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.topMenu)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_home = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_home.sizePolicy().hasHeightForWidth())
        self.btn_home.setSizePolicy(sizePolicy)
        self.btn_home.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.btn_home.setFont(font)
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                              ))
        self.btn_home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_home.setStyleSheet("background-image:\n"
                                    "                                                                                url(:/icons/images/icons/cil-home.png);\n"
                                    "                                                                            ")
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout_8.addWidget(self.btn_home)
        self.btn_processing = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_processing.sizePolicy().hasHeightForWidth())
        self.btn_processing.setSizePolicy(sizePolicy)
        self.btn_processing.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.btn_processing.setFont(font)
        self.btn_processing.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                    ))
        self.btn_processing.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_processing.setStyleSheet("background-image:\n"
                                          "                                                                                url(:/icons/images/icons/cil-layers.png);\n"
                                          "                                                                            ")
        self.btn_processing.setObjectName("btn_processing")
        self.verticalLayout_8.addWidget(self.btn_processing)
        self.btn_output = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_output.sizePolicy().hasHeightForWidth())
        self.btn_output.setSizePolicy(sizePolicy)
        self.btn_output.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.btn_output.setFont(font)
        self.btn_output.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                ))
        self.btn_output.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_output.setStyleSheet("background-image:\n"
                                      "                                                                                url(:/icons/images/icons/cil-file.png);\n"
                                      "                                                                            ")
        self.btn_output.setObjectName("btn_output")
        self.verticalLayout_8.addWidget(self.btn_output)
        self.btn_save = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.btn_save.setFont(font)
        self.btn_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                              ))
        self.btn_save.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_save.setStyleSheet("background-image:\n"
                                    "                                                                                url(:/icons/images/icons/cil-save.png)\n"
                                    "                                                                            ")
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_8.addWidget(self.btn_save)
        self.btn_exit = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_exit.sizePolicy().hasHeightForWidth())
        self.btn_exit.setSizePolicy(sizePolicy)
        self.btn_exit.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.btn_exit.setFont(font)
        self.btn_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                              ))
        self.btn_exit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_exit.setStyleSheet("background-image:\n"
                                    "                                                                                url(:/icons/images/icons/cil-x.png);\n"
                                    "                                                                            ")
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout_8.addWidget(self.btn_exit)
        self.verticalMenuLayout.addWidget(self.topMenu, 0, QtCore.Qt.AlignTop)
        self.bottomMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.bottomMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomMenu.setObjectName("bottomMenu")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.bottomMenu)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.toggleLeftBox = QtWidgets.QPushButton(self.bottomMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleLeftBox.sizePolicy().hasHeightForWidth())
        self.toggleLeftBox.setSizePolicy(sizePolicy)
        self.toggleLeftBox.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.toggleLeftBox.setFont(font)
        self.toggleLeftBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                   ))
        self.toggleLeftBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toggleLeftBox.setStyleSheet("background-image:\n"
                                         "                                                                                url(:/icons/images/icons/icon_settings.png);\n"
                                         "                                                                            ")
        self.toggleLeftBox.setObjectName("toggleLeftBox")
        self.verticalLayout_9.addWidget(self.toggleLeftBox)
        self.verticalMenuLayout.addWidget(self.bottomMenu, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_3.addWidget(self.leftMenuFrame)
        self.appLayout.addWidget(self.leftMenuBg)
        self.extraLeftBox = QtWidgets.QFrame(self.bgApp)
        self.extraLeftBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraLeftBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraLeftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraLeftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraLeftBox.setObjectName("extraLeftBox")
        self.extraColumLayout = QtWidgets.QVBoxLayout(self.extraLeftBox)
        self.extraColumLayout.setContentsMargins(0, 0, 0, 0)
        self.extraColumLayout.setSpacing(0)
        self.extraColumLayout.setObjectName("extraColumLayout")
        self.extraTopBg = QtWidgets.QFrame(self.extraLeftBox)
        self.extraTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.extraTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.extraTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraTopBg.setObjectName("extraTopBg")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.extraTopBg)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.extraTopLayout = QtWidgets.QGridLayout()
        self.extraTopLayout.setContentsMargins(10, -1, 10, -1)
        self.extraTopLayout.setHorizontalSpacing(10)
        self.extraTopLayout.setVerticalSpacing(0)
        self.extraTopLayout.setObjectName("extraTopLayout")
        self.extraIcon = QtWidgets.QFrame(self.extraTopBg)
        self.extraIcon.setMinimumSize(QtCore.QSize(20, 0))
        self.extraIcon.setMaximumSize(QtCore.QSize(20, 20))
        self.extraIcon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraIcon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraIcon.setObjectName("extraIcon")
        self.extraTopLayout.addWidget(self.extraIcon, 0, 0, 1, 1)
        self.extraLabel = QtWidgets.QLabel(self.extraTopBg)
        self.extraLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.extraLabel.setObjectName("extraLabel")
        self.extraTopLayout.addWidget(self.extraLabel, 0, 1, 1, 1)
        self.extraCloseColumnBtn = QtWidgets.QPushButton(self.extraTopBg)
        self.extraCloseColumnBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.extraCloseColumnBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.extraCloseColumnBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.extraCloseColumnBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("\n"
                                     "                                                                                :/icons/images/icons/icon_close.png\n"
                                     "                                                                            "),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.extraCloseColumnBtn.setIcon(icon)
        self.extraCloseColumnBtn.setIconSize(QtCore.QSize(20, 20))
        self.extraCloseColumnBtn.setObjectName("extraCloseColumnBtn")
        self.extraTopLayout.addWidget(self.extraCloseColumnBtn, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.extraTopLayout)
        self.extraColumLayout.addWidget(self.extraTopBg)
        self.extraContent = QtWidgets.QFrame(self.extraLeftBox)
        self.extraContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraContent.setObjectName("extraContent")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.extraContent)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.extraTopMenu = QtWidgets.QFrame(self.extraContent)
        self.extraTopMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraTopMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraTopMenu.setObjectName("extraTopMenu")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.extraTopMenu)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.share_btn = QtWidgets.QPushButton(self.extraTopMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.share_btn.sizePolicy().hasHeightForWidth())
        self.share_btn.setSizePolicy(sizePolicy)
        self.share_btn.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.share_btn.setFont(font)
        self.share_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                               ))
        self.share_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.share_btn.setStyleSheet("background-image:\n"
                                     "                                                                                url(:/icons/images/icons/cil-share-boxed.png);\n"
                                     "                                                                            ")
        self.share_btn.setObjectName("share_btn")
        self.verticalLayout_11.addWidget(self.share_btn)
        self.github_btn = QtWidgets.QPushButton(self.extraTopMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.github_btn.sizePolicy().hasHeightForWidth())
        self.github_btn.setSizePolicy(sizePolicy)
        self.github_btn.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.github_btn.setFont(font)
        self.github_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor
                                                ))
        self.github_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.github_btn.setStyleSheet("background-image:\n"
                                      "                                                                                url(:/icons/images/icons/cil-external-link.png);\n"
                                      "                                                                            ")
        self.github_btn.setObjectName("github_btn")
        self.verticalLayout_11.addWidget(self.github_btn)
        self.verticalLayout_12.addWidget(self.extraTopMenu, 0, QtCore.Qt.AlignTop)
        self.extraCenter = QtWidgets.QFrame(self.extraContent)
        self.extraCenter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraCenter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraCenter.setObjectName("extraCenter")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.extraCenter)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.information_text = QtWidgets.QTextEdit(self.extraCenter)
        self.information_text.setMinimumSize(QtCore.QSize(222, 0))
        self.information_text.setStyleSheet("background:\n"
                                            "                                                                                transparent;\n"
                                            "                                                                            ")
        self.information_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.information_text.setReadOnly(True)
        self.information_text.setObjectName("information_text")
        self.verticalLayout_10.addWidget(self.information_text)
        self.verticalLayout_12.addWidget(self.extraCenter)
        self.extraBottom = QtWidgets.QFrame(self.extraContent)
        self.extraBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraBottom.setObjectName("extraBottom")
        self.verticalLayout_12.addWidget(self.extraBottom)
        self.extraColumLayout.addWidget(self.extraContent)
        self.appLayout.addWidget(self.extraLeftBox)
        self.contentBox = QtWidgets.QFrame(self.bgApp)
        self.contentBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentTopBg = QtWidgets.QFrame(self.contentBox)
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBox = QtWidgets.QFrame(self.contentTopBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy)
        self.leftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBox.setObjectName("leftBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.leftBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titleRightInfo = QtWidgets.QLabel(self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleRightInfo.sizePolicy().hasHeightForWidth())
        self.titleRightInfo.setSizePolicy(sizePolicy)
        self.titleRightInfo.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.titleRightInfo.setFont(font)
