test_config:
    file_path: ./calculator.py
    class: Calculator
    function: uniClassification
    variables: { 'a': int }
    partitions: { 0-39: 'Failed', 40-100: 'Pass' }
    errors: 'Wrong grade.'
