file_path: ./calculator.py
Calculator:
  uniClassification:
    type: method
    EqP: {
      inputs: {
        0: 4,
        1: 45,
        2: 53,
        3: 67,
        4: 79,
      },
      outputs: {
        0: "Failed",
        1: "Pass",
        2: "2:2",
        3: "2:1",
        4: "First!",
      }
    }
    BA: {
      inputs: {
        0: -1,
        1: 0,
        2: 1,
        3: 99,
        4: 100,
        5: 101,
      },
      outputs: {
        0: "Wrong grade.",
        1: "Failed",
        2: "Failed",
        3: "First!",
        4: "First!",
        5: "Wrong grade.",
      }
    }


  carDeals:
    type: static
    PW: {
      inputs: {
        0: [ 'Ford', 20000, 'New' ],
        1: [ 'Volvo', 40000, 'New' ],
        2: [ 'BMW', 50000, 'New' ],
        3: [ 'BMW', 40000, 'Used' ],
        4: [ 'Volvo', 20000, 'Used' ],
        5: [ 'Ford', 50000, 'Used' ],
        6: [ 'Ford', 40000, 'Used' ],
        7: [ 'Volvo', 50000, 'Used' ],
        8: [ 'BMW', 20000, 'Used' ],
      },
      outputs: {
        0: 'Good Deal',
        1: 'Could be better',
        2: 'Could be better',
        3: 'Could be better',
        4: 'Could be better',
        5: 'Bad Deal',
        6: 'Bad Deal',
        7: 'Could be better',
        8: 'Good Deal',
      }

    }
