file_path: ./calculator.py
Calculator:
    uniClassification:
        a:
            partitions: { 0-39: 'Failed',40-49: 'Pass', 50-59: '2-2', 60-69: '2-1', 70-100: 'First' }
            invalid_choices:
                errors: 'Wrong grade.'
        b:
            partitions: { 0-39: 'Failed',40-49: 'Pass', 50-59: '2-2', 60-69: '2-1', 70-100: 'First' }
            invalid_choices:
                errors: 'Wrong grade.'

